version: '3'

services:
  database:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    env_file:
      - ./database/.env
    restart: unless-stopped

  backend:
    build: ./backend
    volumes:
      - ./.prettierrc.json:/var/www/.prettierrc.json
      - ./.prettierignore:/var/www/.prettierignore
      - ./tsconfig-base.json:/var/www/tsconfig-base.json
      - ./shared:/var/www/shared
      - ./backend:/var/www/backend
    ports:
      - 4000:4000
      - 9229:9229
    env_file:
      - ./backend/.env
    environment:
      HOME: '/tmp'
    restart: unless-stopped
    user: ${UID}

  frontend:
    build: ./frontend
    volumes:
      - ./.prettierrc.json:/var/www/.prettierrc.json
      - ./.prettierignore:/var/www/.prettierignore
      - ./tsconfig-base.json:/var/www/tsconfig-base.json
      - ./shared:/var/www/shared
      - ./frontend:/var/www/frontend
    ports:
      - 3000:3000
    environment:
      HOME: '/tmp'
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    user: ${UID}
