version: '3'

services:
  database:
    image: postgres:10-alpine
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}

  backend:
    build: ./backend
    volumes:
      - ./.prettierrc.json:/var/www/.prettierrc.json
      - ./.prettierignore:/var/www/.prettierignore
      - ./tsconfig-base.json:/var/www/tsconfig-base.json
      - ./shared:/var/www/shared
      - ./backend:/var/www/backend
    ports:
      - ${BACKEND_PORT:-4000}:4000
      - ${BACKEND_DEBUG_PORT:-9229}:9229
    environment:
      HOME: '/tmp'
    restart: unless-stopped
    user: ${UID}

  frontend:
    build: ./frontend
    volumes:
      - ./.prettierrc.json:/var/www/.prettierrc.json
      - ./.prettierignore:/var/www/.prettierignore
      - ./tsconfig-base.json:/var/www/tsconfig-base.json
      - ./shared:/var/www/shared
      - ./frontend:/var/www/frontend
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    depends_on:
      - database
    environment:
      HOME: '/tmp'
    restart: unless-stopped
    user: ${UID}

  pg-admin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT:-5050}:80
    env_file:
      - '.env'
    depends_on:
      - database
